apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: self-hosted
  namespace: runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: harleylrn/demo-python
